use car;
CREATE TABLE cars(
		brand_name varchar(40) NOT NULL,
        model_name varchar(40),
        number_id int primary key
    );

select * from cars;

-- MySQL Script generated by MySQL Workbench
-- Sun Apr 23 12:58:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarInsurance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarInsurance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarInsurance` DEFAULT CHARACTER SET utf8 ;
USE `CarInsurance` ;

-- -----------------------------------------------------
-- Table `CarInsurance`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarInsurance`.`owner` (
  `owner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarInsurance`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarInsurance`.`car` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `make` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  `year` DATE NULL,
  `engine_no` VARCHAR(50) NOT NULL,
  `chassis_no` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `owner_id_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `owner_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `CarInsurance`.`owner` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarInsurance`.`policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarInsurance`.`policy` (
  `policy_id` INT NOT NULL AUTO_INCREMENT,
  `car_id` INT NULL,
  `start_date` DATE NULL,
  `end_date` DATE GENERATED ALWAYS AS (start_date + '0001-00-00') VIRTUAL,
  PRIMARY KEY (`policy_id`),
  INDEX `car_id_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `car_id`
    FOREIGN KEY (`car_id`)
    REFERENCES `CarInsurance`.`car` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CarInsurance`.`workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarInsurance`.`workshop` (
  `workshop_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`workshop_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarInsurance`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarInsurance`.`claim` (
  `claim_id` INT NOT NULL AUTO_INCREMENT,
  `policy_no` INT NOT NULL,
  `claim_date` DATE NULL,
  `workshop_id` INT NULL,
  `driver_name` VARCHAR(255) NULL,
  `driver_license_no` VARCHAR(45) NULL,
  PRIMARY KEY (`claim_id`),
  INDEX `policy_no_idx` (`policy_no` ASC) VISIBLE,
  INDEX `workshop_id_idx` (`workshop_id` ASC) VISIBLE,
  CONSTRAINT `policy_no`
    FOREIGN KEY (`policy_no`)
    REFERENCES `CarInsurance`.`policy` (`policy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workshop_id`
    FOREIGN KEY (`workshop_id`)
    REFERENCES `CarInsurance`.`workshop` (`workshop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
